services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql-batch
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - mysql-network

volumes:
  mysql-data:

networks:
  mysql-network:
